# Generated by Django 5.0.14 on 2025-06-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrix', models.TextField()),
                ('normalized_matrix', models.TextField()),
                ('column_sums', models.TextField()),
                ('weights', models.TextField()),
                ('eigen_values', models.TextField()),
                ('lambda_max', models.FloatField()),
                ('CI', models.FloatField()),
                ('CR', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
