# Generated by Django 5.0.14 on 2025-06-08 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BobotKriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kriteria', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MatriksNormalisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_kriteria', models.CharField(max_length=100)),
                ('column_kriteria', models.CharField(max_length=100)),
                ('normalized_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MatriksPerbandingan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_kriteria', models.CharField(max_length=100)),
                ('column_kriteria', models.CharField(max_length=100)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PerhitunganAHP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lambda_max', models.FloatField()),
                ('CI', models.FloatField()),
                ('CR', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Bobot',
        ),
        migrations.AddField(
            model_name='matriksperbandingan',
            name='perhitungan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriks', to='ahp.perhitunganahp'),
        ),
        migrations.AddField(
            model_name='matriksnormalisasi',
            name='perhitungan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalisasi', to='ahp.perhitunganahp'),
        ),
        migrations.AddField(
            model_name='bobotkriteria',
            name='perhitungan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bobot', to='ahp.perhitunganahp'),
        ),
    ]
