# Generated by Django 5.0.14 on 2025-06-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahp', '0002_bobotkriteria_matriksnormalisasi_matriksperbandingan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bobotkriteria',
            name='eigen_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bobotkriteria',
            name='jumlah_kolom',
            field=models.FloatField(default=0),
        ),
    ]
