# Generated by Django 5.0.14 on 2025-06-09 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ahp', '0003_bobotkriteria_eigen_value_bobotkriteria_jumlah_kolom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bobotkriteria',
            old_name='jumlah_kolom',
            new_name='weighted_sum_matrix',
        ),
    ]
