# Generated by Django 5.0.14 on 2025-06-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahp', '0004_rename_jumlah_kolom_bobotkriteria_weighted_sum_matrix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perhitunganahp',
            name='CR',
            field=models.FloatField(default=0),
        ),
    ]
