# Generated by Django 5.0.14 on 2025-06-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahp', '0005_alter_perhitunganahp_cr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perhitunganahp',
            name='CR',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='perhitunganahp',
            name='lambda_max',
            field=models.FloatField(default=0),
        ),
    ]
