# Generated by Django 5.0.14 on 2025-06-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahp', '0006_alter_perhitunganahp_cr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perhitunganahp',
            name='lambda_max',
            field=models.FloatField(),
        ),
    ]
