# Generated by Django 5.0.14 on 2025-06-11 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipk', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('penghasilan_orang_tua', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('jumlah_tanggungan', models.IntegerField(blank=True, null=True)),
                ('usia', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
