# Generated by Django 5.0.14 on 2025-06-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_mahasiswa_penghasilan_orang_tua'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='is_calculated',
            field=models.BooleanField(default=False),
        ),
    ]
