# Generated by Django 5.0.14 on 2025-06-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_mahasiswa_is_calculated'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='total_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
