# Generated by Django 5.0.14 on 2025-06-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_mahasiswa_rank_mahasiswa_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='is_lolos',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
